### ISSUE TITLE
Property 'POLLING_PERIOD' of device 'indi_pylibcamera' not found

### ISSUE THREAD

**Issue by sajmons** [scriptorron/indi_pylibcamera#24]
I came accross this interesting project https://indilib.org/forum/clients/13006-astralite-simple-indi-client-for-astrophotography.html
https://github.com/art-den/astra_lite. I have runed it on Windows 11 and successfully connected to INDI server. But when I tried to take picture it gives me this error. 
![image](https://user-images.githubusercontent.com/7437280/232857433-b4511be2-d96b-40aa-9725-8a3faf2b1641.png)

I'm wandering if this is indi_pylibcamera issue or AstraLite client?

**Comment by scriptorron** [comment]
I asked Denis (developer of astralite) on [https://indilib.org/forum/clients/13006-astralite-simple-indi-client-for-astrophotography.html](https://indilib.org/forum/clients/13006-astralite-simple-indi-client-for-astrophotography.html) about use of POLLING_PERIOD and the new BLOB issue. It is still not sure if the incompatibility is caused by indi_pylibcamera or astralite. We will find a solution :-)

**Comment by scriptorron** [comment]
Denis gave me the hint and I verified POLLING_PERIOD with the CCD Simulator: it seems to set the update rate for telling the exposure progress. The present version of indi_pylibcamera does this every 0.5 seconds fixed. I will implement POLLING_PERIOD to make this adjustable.

It is very annoying that the function of many device properties is not documented. The CCD Simulator helps to get an idea but it is still a guesswork.
